### ISSUE TITLE
iframe performance with showUI: false

### ISSUE THREAD

**Issue by MarshallCB** [MagicHQ/magic-js#78]
## ✨ Feature Request

Load minimal lightweight iframe if showUI is set to false. Loading React + external CSS is unnecessary for custom loading UI's

## 🧩 Context

Trying to build a [login page](https://auth.mediant.co) -- the external UI dependencies for magic link largely outweigh my custom front-end. Performance is a priority, especially for other projects I'd like to incorporate magic link with!

<img width="668" alt="image" src="https://user-images.githubusercontent.com/11445865/80652455-91ae9f80-8a3d-11ea-827a-6fe45d4d4293.png">

Is there any way that an alternative mostly-empty iframe can be loaded if showUI is false? Happy to help, and thanks for providing an awesome developer-experience with this platform!

**Comment by smithki** [comment]
Thanks for contributing! Bundle performance is an issue we're very sensitive to. I'll make sure that lazy-loading our React dependencies is a priority in the next few days.

**Comment by smithki** [comment]
With some smarter code-splitting and lazy-loading UI components, we have a pretty significant improvement!

---

If UI is not necessary for the flow, only the following chunks are loaded

<img width="1097" alt="Screen Shot 2020-05-03 at 11 04 21 AM" src="https://user-images.githubusercontent.com/22753882/80920630-455dab00-8d2e-11ea-8c65-99614c0a17b7.png">

Some of these chunks are also much lighter than before, because they also contained code that was necessary for executing UI.

---

Now, if you do require UI, we lazy load the following additional bundles:

<img width="1013" alt="Screen Shot 2020-05-03 at 11 08 31 AM" src="https://user-images.githubusercontent.com/22753882/80920670-75a54980-8d2e-11ea-86fb-6a21db093c77.png">

---

There are still areas where we can optimize our bundling & code-splitting performance, so I expect we will iterate on this some more. I hope this solves your issue for now 😃
